server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instagram?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sua7308!?
  jpa:
    hibernate:
      ddl-auto: create # application 실행 시점에 기존의 테이블을 지우고 테이블을 새로 생성  (update 는 기존 테이블을 지속적으로 사용한다)
    generate-ddl: true
    show-sql: true # System.out 으로 sql 출력